
GET http://localhost:8080/v1/greeting/Cris
Accept: application/json

### Sync
GET http://localhost:8080/v1/disneyapi/sync
Accept: application/json

### Characters
GET http://localhost:8080/v1/documents/characters
Accept: application/json

### Films
GET http://localhost:8080/v1/documents/films
Accept: application/json

### Process Films
GET http://localhost:8080/v1/documents/process/films
Accept: application/json

### Process VideoGames
GET http://localhost:8080/v1/documents/process/videogames
Accept: application/json

### Process Attractions
GET http://localhost:8080/v1/documents/process/parkAttractions
Accept: application/json

### Process TvShows
GET http://localhost:8080/v1/documents/process/tvShows
Accept: application/json

### Process ShortFilms
GET http://localhost:8080/v1/documents/process/shortFilms
Accept: application/json