
GET http://localhost:8080/v1/greeting/Cris
Accept: application/json

### Sync
GET http://localhost:8080/v1/disneyapi/sync
Accept: application/json

### Characters
GET http://localhost:8080/v1/documents/characters
Accept: application/json

### Films
GET http://localhost:8080/v1/documents/films
Accept: application/json

### Process Films
GET http://localhost:8080/v1/documents/process/films
Accept: application/json

### VideoGames
GET http://localhost:8080/v1/documents/videoGames
Accept: application/json

### Enemies
GET http://localhost:8080/v1/documents/enemies
Accept: application/json